const DIVISIONS = {
    1: {
        name: "Eliteserien 2000",
        teams: [
            {
                id: "valerenga",
                name: "Vålerenga Fotball Elite",
                players: [
                    { "name": "Thomas Sandem", "position": "GK", "age": 25 },
                    { "name": "Øyvind Bolthof", "position": "GK", "age": 21 },
                    { "name": "Mikko Kaven", "position": "GK", "age": 23 },
                    { "name": "Fredrik Kjølner", "position": "DEF", "age": 28 },
                    { "name": "Kent Karlsen", "position": "DEF", "age": 25 },
                    { "name": "Andreas Augustsson", "position": "DEF", "age": 22 },
                    { "name": "Erik Hagen", "position": "DEF", "age": 23 },
                    { "name": "Pa-Modou Kah", "position": "DEF", "age": 18 },
                    { "name": "Knut Henry Haraldsen", "position": "DEF", "age": 22 },
                    { "name": "Tom Henning Hovi", "position": "DEF", "age": 26 },
                    { "name": "Lennart Steffensen", "position": "DEF", "age": 21 },
                    { "name": "Jon Eirik Ødegaard", "position": "DEF", "age": 26 },
                    { "name": "Hai Ngoc Tran", "position": "DEF", "age": 23 },
                    { "name": "Ronny Døhli", "position": "DEF", "age": 20 },
                    { "name": "Joachim Walltin", "position": "MID", "age": 24 },
                    { "name": "Aki Riihilahti", "position": "MID", "age": 22 },
                    { "name": "Kjetil Rekdal", "position": "MID", "age": 30 },
                    { "name": "Bjørn Arild Levernes", "position": "MID", "age": 26 },
                    { "name": "Dag Riisnæs", "position": "MID", "age": 29 },
                    { "name": "Bjørn Viljugrein", "position": "MID", "age": 29 },
                    { "name": "Rune Hagen", "position": "MID", "age": 23 },
                    { "name": "Aasmund Bjørkan", "position": "ATK", "age": 25 },
                    { "name": "Fredrik Thorsen", "position": "ATK", "age": 23 },
                    { "name": "Knut Hovel Heiaas", "position": "ATK", "age": 21 },
                    { "name": "John Carew", "position": "ATK", "age": 19 },
                    { "name": "Pascal Simpson", "position": "ATK", "age": 27 },
                    { "name": "Espen Musæus", "position": "ATK", "age": 23 },
                    { "name": "Kamal Saaliti", "position": "ATK", "age": 19 },
                    { "name": "Kristen Viikmäe", "position": "ATK", "age": 19 }
                ]
            },
            {
                id: "rosenborg",
                name: "Rosenborg BK",
                players: [
                    { "name": "Jørn Jamtfall", "position": "GK", "age": 32 },
                    { "name": "Árni Gautur Arason", "position": "GK", "age": 23 },
                    { "name": "Espen Isaksen", "position": "GK", "age": 19 },
                    { "name": "Tor Eivind Trondsen", "position": "DEF", "age": 22 },
                    { "name": "Martin Høyem", "position": "DEF", "age": 16 },
                    { "name": "Bjørn Otto Bragstad", "position": "DEF", "age": 27 },
                    { "name": "Are Tronseth", "position": "DEF", "age": 17 },
                    { "name": "André Bergdølmo", "position": "DEF", "age": 27 },
                    { "name": "Erik Hoftun", "position": "DEF", "age": 29 },
                    { "name": "Christer Basma", "position": "DEF", "age": 26 },
                    { "name": "Lasse Strand", "position": "DEF", "age": 24 },
                    { "name": "Øyvind Svenning", "position": "DEF", "age": 18 },
                    { "name": "Ståle Stensaas", "position": "DEF", "age": 27 },
                    { "name": "Børge Hernes", "position": "DEF", "age": 22 },
                    { "name": "Mads Skjærvold", "position": "MID", "age": 18 },
                    { "name": "Bent Skammelsrud", "position": "MID", "age": 32 },
                    { "name": "Bent Inge Johnsen", "position": "MID", "age": 26 },
                    { "name": "Roar Strand", "position": "MID", "age": 28 },
                    { "name": "Ørjan Berg", "position": "MID", "age": 30 },
                    { "name": "Fredrik Winsnes", "position": "MID", "age": 23 },
                    { "name": "Kenneth Storvik", "position": "MID", "age": 26 },
                    { "name": "Ole Johan Singsdal", "position": "MID", "age": 19 },
                    { "name": "Mini Jakobsen", "position": "MID", "age": 33 },
                    { "name": "Christer George", "position": "MID", "age": 19 },
                    { "name": "Jan Derek Sørensen", "position": "MID", "age": 27 },
                    { "name": "Øyvind Storflor", "position": "MID", "age": 19 },
                    { "name": "Morten Knutsen", "position": "ATK", "age": 21 },
                    { "name": "Tore André Dahlum", "position": "ATK", "age": 30 },
                    { "name": "Robert Boateng", "position": "ATK", "age": 24 },
                    { "name": "Petter Belsvik", "position": "ATK", "age": 31 },
                    { "name": "John Carew", "position": "ATK", "age": 19 },
                    { "name": "Frode Johnsen", "position": "ATK", "age": 24 },
                    { "name": "Tor Hogne Aarøy", "position": "ATK", "age": 21 },
                    { "name": "Arne Winsnes", "position": "ATK", "age": 24 }
                ]
            },
            {
                id: "viking",
                name: "Viking FK",
                players: [
                    { "name": "Tore Snørteland", "position": "GK", "age": 25 },
                    { "name": "Thomas Solberg", "position": "GK", "age": 25 },
                    { "name": "Lars Gaute Bø", "position": "GK", "age": 35 },
                    { "name": "Bo Andersen", "position": "GK", "age": 22 },
                    { "name": "Odd Arne Espevoll", "position": "DEF", "age": 22 },
                    { "name": "Jan Tore Kleiberg", "position": "DEF", "age": 16 },
                    { "name": "Frode Hansen", "position": "DEF", "age": 26 },
                    { "name": "Hannu Tihinen", "position": "DEF", "age": 22 },
                    { "name": "Audun Helgason", "position": "DEF", "age": 24 },
                    { "name": "Thomas Pereira", "position": "DEF", "age": 25 },
                    { "name": "Jörgen Tengesdal", "position": "DEF", "age": 19 },
                    { "name": "Bjørn Dahl", "position": "DEF", "age": 20 },
                    { "name": "Leif Gunnar Smerud", "position": "MID", "age": 21 },
                    { "name": "Magnus Svensson", "position": "MID", "age": 29 },
                    { "name": "Ronny Kristensen", "position": "MID", "age": 24 },
                    { "name": "Idar Mathiassen", "position": "MID", "age": 22 },
                    { "name": "Trygve Nygaard", "position": "MID", "age": 23 },
                    { "name": "Erik Fuglestad", "position": "MID", "age": 24 },
                    { "name": "Bjarte Lunde Aarsheim", "position": "MID", "age": 23 },
                    { "name": "Tom Sanne", "position": "MID", "age": 23 },
                    { "name": "Martin Knudsen", "position": "MID", "age": 20 },
                    { "name": "Gunnar Aase", "position": "MID", "age": 27 },
                    { "name": "Morten Berre", "position": "MID", "age": 23 },
                    { "name": "Bjørn Berland", "position": "ATK", "age": 21 },
                    { "name": "Erik Nevland", "position": "ATK", "age": 21 },
                    { "name": "Patrick Holtet", "position": "ATK", "age": 17 },
                    { "name": "Ríkhardur Dadason", "position": "ATK", "age": 26 },
                    { "name": "Trond Heggestad", "position": "ATK", "age": 20 }
                ]
            },
            {
                id: "start",
                name: "IK Start",
                players: [
                    { "name": "Rune Nilssen", "position": "GK", "age": 23 },
                    { "name": "Espen Johnsen", "position": "GK", "age": 19 },
                    { "name": "Dag Tore Fredriksen", "position": "GK", "age": 18 },
                    { "name": "Tom Morten Hammerborg", "position": "DEF", "age": 27 },
                    { "name": "Sven Kloster", "position": "DEF", "age": 28 },
                    { "name": "Preben Gundersen", "position": "DEF", "age": 21 },
                    { "name": "Björn Stephansen", "position": "DEF", "age": 24 },
                    { "name": "Trond Nordseth", "position": "DEF", "age": 24 },
                    { "name": "Knut Kløvvik", "position": "DEF", "age": 28 },
                    { "name": "Roger Simonsen", "position": "DEF", "age": 22 },
                    { "name": "Helge Bjönsaas", "position": "DEF", "age": 30 },
                    { "name": "Tom Reidar Haraldsen", "position": "DEF", "age": 18 },
                    { "name": "Kristian Sörli", "position": "DEF", "age": 22 },
                    { "name": "Tom Berhus", "position": "MID", "age": 23 },
                    { "name": "Valdo Nyabaro", "position": "MID", "age": 21 },
                    { "name": "Lee Robertson", "position": "MID", "age": 25 },
                    { "name": "Ousman Nyan", "position": "MID", "age": 23 },
                    { "name": "Roger Risholt", "position": "MID", "age": 19 },
                    { "name": "Terje Ellingsen", "position": "MID", "age": 27 },
                    { "name": "Stian Ohr", "position": "MID", "age": 20 },
                    { "name": "Harald Lödemel", "position": "ATK", "age": 24 },
                    { "name": "Terje Leonardsen", "position": "ATK", "age": 22 },
                    { "name": "Raymond Hofstædter", "position": "ATK", "age": 19 },
                    { "name": "Andreas Ottosson", "position": "ATK", "age": 27 }
                ]
            },
            {
                id: "lillestrom",
                name: "Lillestrøm SK",
                players: [
                    { "name": "Per Magne Misund", "position": "GK", "age": 27 },
                    { "name": "Tor André Grenersen", "position": "GK", "age": 29 },
                    { "name": "Emile Baron", "position": "GK", "age": 19 },
                    { "name": "Clas André Guttulsrød", "position": "GK", "age": 27 },
                    { "name": "Frank Arne Hauge", "position": "DEF", "age": 18 },
                    { "name": "Peter Werni", "position": "DEF", "age": 24 },
                    { "name": "Torgeir Bjarmann", "position": "DEF", "age": 30 },
                    { "name": "Ármann Björnsson", "position": "DEF", "age": 17 },
                    { "name": "Indridi Sigurdsson", "position": "DEF", "age": 17 },
                    { "name": "Tommy Berntsen", "position": "DEF", "age": 25 },
                    { "name": "Olav Zanetti", "position": "DEF", "age": 22 },
                    { "name": "Torjus Hansén", "position": "DEF", "age": 25 },
                    { "name": "Roger Helland", "position": "MID", "age": 25 },
                    { "name": "Stian Berget", "position": "MID", "age": 21 },
                    { "name": "Kjetil Nilsen", "position": "MID", "age": 23 },
                    { "name": "Jarkko Wiss", "position": "MID", "age": 26 },
                    { "name": "Einar Thór Daníelsson", "position": "MID", "age": 28 },
                    { "name": "Magnus Kihlberg", "position": "MID", "age": 25 },
                    { "name": "Espen Haug", "position": "MID", "age": 23 },
                    { "name": "Espen Søgård", "position": "MID", "age": 19 },
                    { "name": "Pal Strand", "position": "MID", "age": 22 },
                    { "name": "Rúnar Kristinsson", "position": "MID", "age": 29 },
                    { "name": "Sveinung Fjeldstad", "position": "ATK", "age": 20 },
                    { "name": "Magnus Powell", "position": "ATK", "age": 24 },
                    { "name": "Arild Sundgot", "position": "ATK", "age": 20 },
                    { "name": "Grétar Ólafur Hjartarson", "position": "ATK", "age": 21 }
                ]
            },
            {
                id: "bodo_glimt",
                name: "FK Bodø / Glimt",
                players: [
                    { "name": "Tor Egil Horn", "position": "GK", "age": 22 },
                    { "name": "Clas André Guttulsrød", "position": "GK", "age": 27 },
                    { "name": "Rohnny Westad", "position": "GK", "age": 26 },
                    { "name": "Håvard Halvorsen", "position": "DEF", "age": 25 },
                    { "name": "Helge Aune", "position": "DEF", "age": 25 },
                    { "name": "Christian Steen", "position": "DEF", "age": 21 },
                    { "name": "Cato André Hansen", "position": "DEF", "age": 26 },
                    { "name": "Thomas Jacobsen", "position": "DEF", "age": 15 },
                    { "name": "Andreas Evjen", "position": "DEF", "age": 29 },
                    { "name": "Thor Mikalsen", "position": "DEF", "age": 25 },
                    { "name": "Thomas Breivik", "position": "DEF", "age": 21 },
                    { "name": "Kristoffer Vatshaug", "position": "DEF", "age": 17 },
                    { "name": "Arild Berg", "position": "MID", "age": 23 },
                    { "name": "Eirik Dybendal", "position": "MID", "age": 20 },
                    { "name": "Lee Robertson", "position": "MID", "age": 25 },
                    { "name": "Erling Kjøen", "position": "MID", "age": 25 },
                    { "name": "Tom Kare Staurvik", "position": "MID", "age": 28 },
                    { "name": "Bjørn Arve Lund", "position": "MID", "age": 17 },
                    { "name": "Christian Berg", "position": "MID", "age": 20 },
                    { "name": "André Hanssen", "position": "MID", "age": 17 },
                    { "name": "Tommy Bergersen", "position": "MID", "age": 26 },
                    { "name": "Trond Ludvigsen", "position": "MID", "age": 16 },
                    { "name": "Aasmund Bjørkan", "position": "ATK", "age": 25 },
                    { "name": "Håvard Sakariassen", "position": "ATK", "age": 22 },
                    { "name": "Bengt Sæternes", "position": "ATK", "age": 23 },
                    { "name": "Eivind Eriksen", "position": "ATK", "age": 25 }
                ]
            },
            {
                id: "molde",
                name: "Molde FK",
                players: [
                    { "name": "Morten Bakke", "position": "GK", "age": 30 },
                    { "name": "Are Lervik", "position": "GK", "age": 26 },
                    { "name": "Knut Lillebakk", "position": "GK", "age": 20 },
                    { "name": "Stale Rönningen", "position": "DEF", "age": 20 },
                    { "name": "Erlend Ormbostad", "position": "DEF", "age": 17 },
                    { "name": "Petter Christian Singsaas", "position": "DEF", "age": 26 },
                    { "name": "Fredrik Kjølner", "position": "DEF", "age": 28 },
                    { "name": "Trond Andersen", "position": "DEF", "age": 23 },
                    { "name": "Roger Nilsen", "position": "DEF", "age": 29 },
                    { "name": "Knud Anders Fostervold", "position": "DEF", "age": 27 },
                    { "name": "Torgeir Ruud Ramsli", "position": "DEF", "age": 19 },
                    { "name": "Trond Strande", "position": "DEF", "age": 28 },
                    { "name": "Pål Lydersen", "position": "DEF", "age": 33 },
                    { "name": "Dennis Schiller", "position": "DEF", "age": 33 },
                    { "name": "Freddy dos Santos", "position": "DEF", "age": 22 },
                    { "name": "Stig Arild Raket", "position": "MID", "age": 20 },
                    { "name": "Jonny M. Hansen", "position": "MID", "age": 17 },
                    { "name": "Jarkko Wiss", "position": "MID", "age": 26 },
                    { "name": "Daniel Berg Hestad", "position": "MID", "age": 23 },
                    { "name": "Thomas Mork", "position": "MID", "age": 20 },
                    { "name": "Svein Tore Brandshaug", "position": "MID", "age": 19 },
                    { "name": "Anders Hasselgard", "position": "MID", "age": 20 },
                    { "name": "Tor Einar Leira", "position": "MID", "age": 17 },
                    { "name": "Jo Tessem", "position": "MID", "age": 26 },
                    { "name": "Karl Oskar Fjørtoft", "position": "MID", "age": 23 },
                    { "name": "Magne Hoseth", "position": "MID", "age": 18 },
                    { "name": "Martin Andresen", "position": "MID", "age": 21 },
                    { "name": "Petter Rudi", "position": "MID", "age": 25 },
                    { "name": "Odd Inge Olsen", "position": "MID", "age": 29 },
                    { "name": "Ole Bjørn Sundgot", "position": "ATK", "age": 26 },
                    { "name": "Clayton Zane", "position": "ATK", "age": 21 },
                    { "name": "Bernt Hulsker", "position": "ATK", "age": 21 },
                    { "name": "Andreas Lund", "position": "ATK", "age": 23 },
                    { "name": "André Schei Lindbæk", "position": "ATK", "age": 21 },
                    { "name": "Nils Gunnar Thomle", "position": "ATK", "age": 17 }
                ]
            },
            {
                id: "bryne",
                name: "Bryne FK",
                players: [
                    { "name": "Roger Eskeland", "position": "GK", "age": 21 },
                    { "name": "Svein Bö", "position": "GK", "age": 27 },
                    { "name": "Knut Sirevåg", "position": "DEF", "age": 20 },
                    { "name": "Pal Håpnes", "position": "DEF", "age": 28 },
                    { "name": "Jørgen Rangnes", "position": "DEF", "age": 26 },
                    { "name": "Einar Braut", "position": "DEF", "age": 23 },
                    { "name": "Anders Friberg", "position": "DEF", "age": 23 },
                    { "name": "Ragnvald Soma", "position": "DEF", "age": 19 },
                    { "name": "Ole Hjelmhaug", "position": "DEF", "age": 22 },
                    { "name": "Thomas Berntsen", "position": "DEF", "age": 28 },
                    { "name": "Jonas Jonsson", "position": "MID", "age": 22 },
                    { "name": "Hallgeir Hinna", "position": "MID", "age": 28 },
                    { "name": "Andreas Nygård", "position": "MID", "age": 16 },
                    { "name": "Trond Björnsen", "position": "MID", "age": 23 },
                    { "name": "Kenneth Giske", "position": "MID", "age": 22 },
                    { "name": "Peter Olofsson", "position": "MID", "age": 23 },
                    { "name": "Kai Ove Stokkeland", "position": "MID", "age": 20 },
                    { "name": "Geir Atle Undheim", "position": "ATK", "age": 25 },
                    { "name": "Rune Medalen", "position": "ATK", "age": 28 },
                    { "name": "Thomas Dahl", "position": "ATK", "age": 30 },
                    { "name": "Eivind Karlsbakk", "position": "ATK", "age": 23 },
                    { "name": "Bent Apneseth", "position": "ATK", "age": 29 }
                ]
            },
            {
                id: "odd",
                name: "Odd Grenland",
                players: [
                    { "name": "Erik Holtan", "position": "GK", "age": 29 },
                    { "name": "Svein Roger Dahlen", "position": "GK", "age": 24 },
                    { "name": "Brede Bomhoff", "position": "DEF", "age": 22 },
                    { "name": "Jørn Marius Therkelsen", "position": "DEF", "age": 27 },
                    { "name": "Tom Morten Hammerborg", "position": "DEF", "age": 27 },
                    { "name": "Ronny Deila", "position": "DEF", "age": 23 },
                    { "name": "Morten Fevang", "position": "DEF", "age": 23 },
                    { "name": "Alexander Aas", "position": "DEF", "age": 20 },
                    { "name": "Jan Frode Nornes", "position": "DEF", "age": 25 },
                    { "name": "Bård Borgersen", "position": "DEF", "age": 26 },
                    { "name": "Anders Rambekk", "position": "DEF", "age": 22 },
                    { "name": "Jan Gunnar Solli", "position": "DEF", "age": 17 },
                    { "name": "Thomas Röed", "position": "MID", "age": 24 },
                    { "name": "Christian Flindt Bjerg", "position": "MID", "age": 24 },
                    { "name": "Sami Mahlio", "position": "MID", "age": 26 },
                    { "name": "Erik Pedersen", "position": "MID", "age": 31 },
                    { "name": "Espen Hoff", "position": "MID", "age": 17 },
                    { "name": "Armin Sistek", "position": "ATK", "age": 15 },
                    { "name": "Frode Johnsen", "position": "ATK", "age": 24 },
                    { "name": "Martin Wiig", "position": "ATK", "age": 15 },
                    { "name": "Erik Bo Andersen", "position": "ATK", "age": 28 },
                    { "name": "Kim Larsen", "position": "ATK", "age": 22 },
                    { "name": "Kristian Bye-Andersen", "position": "ATK", "age": 23 },
                    { "name": "Bard André Nilssen", "position": "ATK", "age": 18 },
                    { "name": "Arne Sandstø", "position": "ATK", "age": 32 },
                    { "name": "Tor Gunnar Johnsen", "position": "ATK", "age": 27 }
                ]
            },
            {
                id: "brann",
                name: "SK Brann",
                players: [
                    { "name": "Magnus Kihlstedt", "position": "GK", "age": 26 },
                    { "name": "Håkon Opdal", "position": "GK", "age": 16 },
                    { "name": "Geir Hakon Valland", "position": "GK", "age": 20 },
                    { "name": "Kjell Andreas Olsen", "position": "GK", "age": 29 },
                    { "name": "Ivar Rønningen", "position": "GK", "age": 23 },
                    { "name": "Marcus Bakke", "position": "DEF", "age": 17 },
                    { "name": "Arne Vidar Moen", "position": "DEF", "age": 27 },
                    { "name": "Roy Wassberg", "position": "DEF", "age": 28 },
                    { "name": "Knut Walde", "position": "DEF", "age": 17 },
                    { "name": "Harri Ylönen", "position": "DEF", "age": 27 },
                    { "name": "Per-Ove Ludvigsen", "position": "DEF", "age": 32 },
                    { "name": "Egil Ulfstein", "position": "DEF", "age": 27 },
                    { "name": "Hassan El Fakiri", "position": "DEF", "age": 21 },
                    { "name": "Erlend Hanstveit", "position": "DEF", "age": 17 },
                    { "name": "Cato Guntveit", "position": "DEF", "age": 23 },
                    { "name": "Geirmund Brendesæter", "position": "DEF", "age": 28 },
                    { "name": "Roger Helland", "position": "MID", "age": 25 },
                    { "name": "John Erik Indrebø", "position": "MID", "age": 20 },
                    { "name": "Per Mikkel Haldorsen", "position": "MID", "age": 16 },
                    { "name": "Kjetil Norland", "position": "MID", "age": 20 },
                    { "name": "Morten Kolseth", "position": "MID", "age": 19 },
                    { "name": "Svante Samuelsson", "position": "MID", "age": 26 },
                    { "name": "Jan Ove Pedersen", "position": "MID", "age": 30 },
                    { "name": "Stefan Paldan", "position": "MID", "age": 27 },
                    { "name": "Tomas Ražanauskas", "position": "MID", "age": 22 },
                    { "name": "Tommy Knarvik", "position": "MID", "age": 19 },
                    { "name": "Martin Knudsen", "position": "MID", "age": 20 },
                    { "name": "Sergei Terehhov", "position": "MID", "age": 23 },
                    { "name": "Raymond Kvisvik", "position": "MID", "age": 24 },
                    { "name": "Alex Valencia", "position": "MID", "age": 19 },
                    { "name": "Mika Kottila", "position": "ATK", "age": 24 },
                    { "name": "Kjetil Løvvik", "position": "ATK", "age": 26 },
                    { "name": "Mons Ivar Mjelde", "position": "ATK", "age": 31 },
                    { "name": "Azar Karadas", "position": "ATK", "age": 17 },
                    { "name": "Petter Andreassen", "position": "ATK", "age": 20 },
                    { "name": "Pal Kristian Økland", "position": "ATK", "age": 20 },
                    { "name": "Thorstein Helstad", "position": "ATK", "age": 21 }
                ]
            },
            {
                id: "stabaek",
                name: "Stabæk Fotball",
                players: [
                    { "name": "Frode Olsen", "position": "GK", "age": 31 },
                    { "name": "Jon Knudsen", "position": "GK", "age": 24 },
                    { "name": "Anders Rotevatn", "position": "GK", "age": 20 },
                    { "name": "Christian Holter", "position": "DEF", "age": 26 },
                    { "name": "Niclas Svensson", "position": "DEF", "age": 28 },
                    { "name": "John Arvid Skistad", "position": "DEF", "age": 30 },
                    { "name": "André Flem", "position": "DEF", "age": 31 },
                    { "name": "Mike Kjølø", "position": "DEF", "age": 27 },
                    { "name": "Inge André Olsen", "position": "DEF", "age": 20 },
                    { "name": "André Muri", "position": "DEF", "age": 17 },
                    { "name": "Tom Stenvoll", "position": "DEF", "age": 20 },
                    { "name": "Lennart Steffensen", "position": "DEF", "age": 21 },
                    { "name": "Pétur Haflidi Marteinsson", "position": "DEF", "age": 25 },
                    { "name": "Christian Michelsen", "position": "MID", "age": 22 },
                    { "name": "Tommy Svindal Larsen", "position": "MID", "age": 25 },
                    { "name": "Tobias Linderoth", "position": "MID", "age": 19 },
                    { "name": "Richard Ackon", "position": "MID", "age": 20 },
                    { "name": "Andreas Hauger", "position": "MID", "age": 19 },
                    { "name": "Axel Kolle", "position": "MID", "age": 25 },
                    { "name": "Martin Andresen", "position": "MID", "age": 21 },
                    { "name": "Tommy Stenersen", "position": "MID", "age": 22 },
                    { "name": "David Hanssen", "position": "MID", "age": 22 },
                    { "name": "Christian Wilhelmsson", "position": "MID", "age": 19 },
                    { "name": "Thomas Finstad", "position": "ATK", "age": 20 },
                    { "name": "Petter Belsvik", "position": "ATK", "age": 31 },
                    { "name": "Dennis Iliohan", "position": "ATK", "age": 26 },
                    { "name": "Marel Jóhann Baldvinsson", "position": "ATK", "age": 18 }
                ]
            },
            {
                id: "tromso",
                name: "Tromsø IL",
                players: [
                    { "name": "Thomas Töllefsen", "position": "GK", "age": 25 },
                    { "name": "Knut Borch", "position": "GK", "age": 18 },
                    { "name": "Lars Nymo Trulsen", "position": "DEF", "age": 22 },
                    { "name": "Svein Morten Johansen", "position": "DEF", "age": 27 },
                    { "name": "Roger Lange", "position": "DEF", "age": 29 },
                    { "name": "Miika Koppinen", "position": "DEF", "age": 20 },
                    { "name": "Robin Berntsen", "position": "DEF", "age": 28 },
                    { "name": "Leif Arne Brekke", "position": "DEF", "age": 21 },
                    { "name": "Marko Tuomela", "position": "DEF", "age": 26 },
                    { "name": "Ole Talberg", "position": "DEF", "age": 16 },
                    { "name": "Morten Kraemer", "position": "DEF", "age": 31 },
                    { "name": "Jan Egil Brekke", "position": "DEF", "age": 24 },
                    { "name": "Thomas Hafstad", "position": "DEF", "age": 24 },
                    { "name": "Gaute Helstrup", "position": "MID", "age": 22 },
                    { "name": "Jonny Hanssen", "position": "MID", "age": 26 },
                    { "name": "Frode Fermann", "position": "MID", "age": 23 },
                    { "name": "Roar Christensen", "position": "MID", "age": 27 },
                    { "name": "Morten Gamst Pedersen", "position": "MID", "age": 17 },
                    { "name": "Ole Andreas Nilsen", "position": "MID", "age": 22 },
                    { "name": "Morten Giaever", "position": "MID", "age": 16 },
                    { "name": "Olav Rastad", "position": "MID", "age": 19 },
                    { "name": "Abdoulaye M'Baye", "position": "ATK", "age": 25 },
                    { "name": "Rune Berger", "position": "ATK", "age": 20 },
                    { "name": "Tryggvi Gudmundsson", "position": "ATK", "age": 24 },
                    { "name": "Rune Lange", "position": "ATK", "age": 21 }
                ]
            },
            {
                id: "haugesund",
                name: "FK Haugesund",
                players: [
                    { "name": "Rune Solhaug", "position": "GK", "age": 17 },
                    { "name": "Per Andreas Haftorsen", "position": "GK", "age": 28 },
                    { "name": "Kenneth Høie", "position": "GK", "age": 19 },
                    { "name": "Eirik Horneland", "position": "DEF", "age": 23 },
                    { "name": "Thormod Edward Ness", "position": "DEF", "age": 26 },
                    { "name": "Tor Age Larsen", "position": "DEF", "age": 26 },
                    { "name": "Knut Olav Ystaas", "position": "DEF", "age": 24 },
                    { "name": "Ervin Horn", "position": "DEF", "age": 20 },
                    { "name": "Stig Kallestad", "position": "DEF", "age": 19 },
                    { "name": "Sindre Eid", "position": "DEF", "age": 24 },
                    { "name": "Rune André Vindheim", "position": "DEF", "age": 26 },
                    { "name": "Stefan Mogren", "position": "DEF", "age": 30 },
                    { "name": "Arild Andersen", "position": "DEF", "age": 26 },
                    { "name": "Kent Karlsen", "position": "DEF", "age": 25 },
                    { "name": "Trond Erik Bertelsen", "position": "DEF", "age": 14 },
                    { "name": "Asbjörn Helgeland", "position": "MID", "age": 32 },
                    { "name": "Tarje Nordstrand Jacobsen", "position": "MID", "age": 24 },
                    { "name": "Steinar Lein", "position": "MID", "age": 27 },
                    { "name": "Magnus Samuelsson", "position": "MID", "age": 26 },
                    { "name": "Petter Sevel", "position": "MID", "age": 24 },
                    { "name": "Asle Andersen", "position": "MID", "age": 26 },
                    { "name": "Christian Grindheim", "position": "MID", "age": 15 },
                    { "name": "Geir Tharaldsen", "position": "ATK", "age": 20 },
                    { "name": "Hans Berggren", "position": "ATK", "age": 25 },
                    { "name": "Anders Blomquist", "position": "ATK", "age": 21 },
                    { "name": "Jarle Wee", "position": "ATK", "age": 26 },
                    { "name": "Rune Wiken", "position": "ATK", "age": 18 },
                    { "name": "Bala Ahmed Garba", "position": "ATK", "age": 24 }
                ]
            },
            {
                id: "moss",
                name: "Moss FK",
                players: [
                    { "name": "Rino André Hansen", "position": "GK", "age": 28 },
                    { "name": "Per Morten Kristiansen", "position": "GK", "age": 17 },
                    { "name": "Pål Anders Stubsveen", "position": "DEF", "age": 17 },
                    { "name": "Lars Habberstad", "position": "DEF", "age": 18 },
                    { "name": "Carsten Johansen", "position": "DEF", "age": 29 },
                    { "name": "Christian Petersen", "position": "DEF", "age": 20 },
                    { "name": "Anders Juliussen", "position": "DEF", "age": 22 },
                    { "name": "Tom Morten Hammerborg", "position": "DEF", "age": 27 },
                    { "name": "Tor Eivind Trondsen", "position": "DEF", "age": 22 },
                    { "name": "Rune Tangen", "position": "DEF", "age": 34 },
                    { "name": "Jörgen Pettersen", "position": "DEF", "age": 17 },
                    { "name": "Jan Tore Ophaug", "position": "DEF", "age": 21 },
                    { "name": "Johan Petter Winsnes", "position": "DEF", "age": 23 },
                    { "name": "Gard Kristiansen", "position": "MID", "age": 26 },
                    { "name": "Tor Egil Hansen", "position": "MID", "age": 27 },
                    { "name": "Magnus Amundsen", "position": "MID", "age": 17 },
                    { "name": "Jarkko Wiss", "position": "MID", "age": 26 },
                    { "name": "Kent Bergersen", "position": "MID", "age": 31 },
                    { "name": "Hans Erik Ramberg", "position": "MID", "age": 22 },
                    { "name": "Simen Brenne", "position": "MID", "age": 17 },
                    { "name": "Dagfinn Enerly", "position": "MID", "age": 26 },
                    { "name": "Christian Johnsen", "position": "ATK", "age": 21 },
                    { "name": "Kjell Ove Olofsson", "position": "ATK", "age": 33 },
                    { "name": "Hans Palmquist", "position": "ATK", "age": 31 },
                    { "name": "Joakim Petter Hermansen", "position": "ATK", "age": 19 },
                    { "name": "Benjamin Bruun", "position": "ATK", "age": 20 },
                    { "name": "Aaron Wilbraham", "position": "ATK", "age": 19 },
                    { "name": "Jerry Mansson", "position": "ATK", "age": 26 }
                ]
            }
        ]
    }
};

export default DIVISIONS;