export const NORWEGIAN_NAMES = {
  male: [
    'Adam', 'Adrian', 'Albert', 'Alexander', 'Alf', 'Alfred', 'Allan', 'Amund', 'Anders', 'Andreas',
    'Andre', 'Ansgar', 'Anton', 'Are', 'Arild', 'Arne', 'Arnold', 'Arnt', 'Arthur', 'Arvid',
    'Asbjørn', 'Asgeir', 'Ask', 'Atle', 'Audun', 'August',
    'Bard', 'Bastian', 'Bendik', 'Bent', 'Bent Inge', 'Bernt', 'Bjarne', 'Bjørnar', 'Bjørn', 'Birger', 'Bo', 'Brage', 'Bror', 'Brynjar', 'Børre', 'Børge',
    ['Carl', 'Karl'], ['Christian', 'Kristian'], 'Casper', 'Cato', 'Christer', 'Christoffer', 'Claus',
    'Dag', 'Dag Frode', 'Dagfinn', 'Daniel', 'Dan', 'David', 'Dennis', 'Didrik',
    'Edvard', 'Egil', 'Eilert', 'Einar', 'Eirik', 'Eivind', 'Emil', 'Endre', 'Erik', 'Erling', 'Erlend', 'Elling', 'Eskil', 'Espen', 'Even',
    'Fabian', 'Felix', 'Filip', 'Frank', 'Frans', 'Fred', 'Fredrik', 'Frode',
    'Gabriel', 'Gard', 'Gaute', 'Geir', 'Georg', 'Gerhard', 'Gisle', 'Glenn', 'Gunnar', 'Gunvald', 'Gustav',
    'Halvard', 'Hallgeir', 'Hans', 'Harald', 'Harry', 'Helge', 'Henning', 'Henrik', 'Herman', 'Hjalmar', 'Håkon', 'Håvard', 'Hilmar',
    'Idar', 'Inge', 'Ingar', 'Ingmar', 'Ingolf', 'Ingvar', 'Isak', 'Iver',
    'Jakob', 'Jan', 'Jan Derek', 'Jarle', 'Jens', 'Jo', 'Jo Sondre', 'Joakim', 'Joachim', 'Joar', 'Johan', 'Johannes', 'John', 'Johnny', 'Jon', 'Jonas', 'Jonatan', 'Jostein', 'Julian', 'Julius', 'Jørgen',
    'Kai', 'Kaj', 'Karsten', 'Kåre', 'Kasper', 'Kenneth', 'Ketil', 'Kim', 'Kjartan', 'Kjetil', 'Kjell', 'Knut', 'Konrad', 'Kristoffer', 'Kurt', 'Kyrre',
    'Lars', 'Lasse', 'Laurits', 'Leander', 'Leif', 'Leon', 'Loke', 'Lorents', 'Ludvig', 'Lukas', 'Linus', 'Magne', 'Magnus', 'Mads', 'Malte', 'Marcus', 'Markus', 'Marius', 'Martin', 'Mathias', 'Mats', 'Mikael', 'Mikkel', 'Mons', 'Morten',
    'Natan', 'Niclas', 'Nicolai', 'Niels', 'Niklas', 'Nikolai', 'Nils', 'Noah', 'Normann', 'Njål',
    'Odd', 'Oddgeir', 'Oddmund', 'Odd Inge', 'Oddvar',
    'Odin', 'Ola', 'Olaf', 'Ole', 'Ole Johan', 'Oliver', 'Olav', 'Olaus', 'Oscar', 'Oskar', 'Ove', 'Ørjan', 'Øyvind', 'Øystein', 'Otto',
    'Pål', 'Pål-André', 'Patrick', 'Paul', 'Peder', 'Per', 'Per Ciljan', 'Petter', 'Preben', 'Philip', 'Pelle',
    'Ragnar', 'Ralph', 'Reidar', 'Richard', 'Rickard', 'Roald', 'Roar', 'Robert', 'Roger', 'Roland', 'Rolf', 'Ronny', 'Roy', 'Rune', 'Runar', 'Ruben', 'Rudolf', 'Rasmus',
    'Samuel', 'Sebastian', 'Sigbjørn', 'Sigmund', 'Sigurd', 'Simen', 'Simon', 'Sindre', 'Sivert', 'Sjur', 'Stefan', 'Steffen', 'Stein', 'Steinar', 'Stian', 'Stig', 'Svein', 'Sverre', 'Sturla', 'Syver',
    'Tarald', 'Tarjei', 'Terje', 'Theodor', 'Thomas', 'Thor', 'Tobias', 'Tom', 'Tommy', 'Tomas', 'Tor', 'Toralf', 'Torbjørn', 'Tord', 'Torgeir', 'Tor Erik', 'Torjus', 'Torkel', 'Tormod', 'Torstein', 'Tore', 'Trond', 'Trygve', 'Trym',
    'Ulf', 'Ulrik',
    'Verner', 'Vegard', 'Vemund', 'Vidar', 'Viggo', 'Vilhelm', 'Viljar', 'Viktor', 'Vincent',
    'Walter', 'Waldemar', 'Werner', 'Wilhelm', 'William', 'Wiktor', 'Willy',
    'Yngve', 'Yngvar',
    'Ådne', 'Åge', 'Åsmund', 'Åsen',
    'Øivind', 'Ørnulf',
  ],
  female: [
    'Adele', 'Ada', 'Agnes', 'Aisha', 'Alma', 'Alvilde', 'Amalie', 'Amira', 'Anette', 'Anja', 'Anita',
    'Anneli', 'Anni', 'Annika', 'Anniken', 'Aud', 'Aurora', 'Aina', 'Annbjørg', 'Alfhild', 'Arnhild',
    'Barbara', 'Benedicte', 'Berit', 'Bodil', 'Bjørg', 'Bente', 'Birgitte', 'Brynhild', 'Borghild', 'Bjørnarine',
    'Camilla', 'Carina', 'Caroline', 'Cecilie', 'Charlotte', 'Christine', ['Catherine', 'Katrine', 'Katarina'], 'Chloe', 'Clara', 'Cynthia',
    'Dina', 'Diana', 'Dorothy', 'Dora', 'Dagny', 'Dorthe', 'Disa', 'Dorte', 'Dina-Marie', 'Desiree',
    ['Eli', 'Elin'], ['Emilie', 'Emilia'], 'Eira', 'Eivor', 'Elaine', 'Elida', 'Elise', 'Ella', 'Ellen',
    'Elina', 'Emily', 'Emma', 'Erika', 'Eva', 'Evelyn', 'Edle', 'Edel', 'Eivinda', 'Elenora',
    'Fatima', 'Frida', 'Freja', 'Freya', 'Fjolla', 'Filippa', 'Frodehild', 'Fride', 'Frøydis', 'Fanny',
    'Gabriella', 'Gina', 'Gjertrud', 'Greta', 'Gunn', 'Gunhild', 'Gry', 'Gro', 'Grynet', 'Gudrun',
    'Hanna', 'Hanne', 'Hedda', 'Heidi', 'Helen', 'Helene', 'Helga', 'Hilde', 'Hanne-Lise', 'Hanne-Mari',
    'Ida', 'Inga', 'Inger', 'Ingrid', 'Ingvild', 'Iselin', 'Isabel', 'Irene', 'Ivy', 'Ingfrid',
    'Jakobine', 'Jane', 'Janne', 'Jeanette', 'Jenny', 'Joanna', 'Julie', 'June', 'Juni', 'Juliet',
    'Jorunn', 'Josefine', 'Johanne', 'Jorid', 'Jannike',
    'Kaja', 'Karen', 'Karina', 'Karoline', 'Katrin', 'Kristin', 'Kristina', 'Kristine', 'Kine', 'Kjersti',
    'Kari', 'Kirsten', 'Kirsti', 'Klara', 'Katrine-Marie',
    'Lena', 'Leah', 'Lea', 'Lene', 'Lilly', 'Linn', 'Linnea', 'Liv', 'Louise', 'Lotte',
    'Lovise', 'Lillian', 'Lina', 'Lisbet', 'Lone',
    'Maja', 'Malin', 'Maren', 'Maria', 'Marianne', 'Marie', 'Marthe', 'Mathea', 'Martine', 'Mathilde', 'Melina',
    'Mia', 'Michelle', 'Mina', 'Mona', 'Marlene',
    'Nina', 'Noor', 'Nora', 'Nina-Marie', 'Nicoline', 'Nadja', 'Norunn', 'Nanna', 'Nydia', 'Nille',
    'Oda', 'Olivia', 'Oline', 'Otilie', 'Ovidia', 'Othilie', 'Oda-Louise', 'Othilia', 'Olina', 'Odine',
    'Rikke', 'Ronja', 'Ragnhild', 'Ragna', 'Ruth', 'Rakel', 'Randi', 'Rebekka', 'Rim', 'Runa',
    'Sara', 'Selma', 'Signe', 'Sigrid', 'Silje', 'Sofie', 'Stine', 'Synne', 'Siv', 'Synnøve', 'Solfrid',
    'Thea', 'Tiril', 'Tuva', 'Trine', 'Tove', 'Tone', 'Tora', 'Thale', 'Tina', 'Tiril-Marie',
    'Una', 'Ulla', 'Ulrikke', 'Unni', 'Urd', 'Ulla-Marie', 'Ulla-Lise', 'Ulrika', 'Unice', 'Udele',
    'Vilde', 'Vilja', 'Vilje', 'Vera', 'Veronica', 'Vibeke', 'Vår', 'Vibeke-Marie', 'Vanja', 'Vivian',
    'Ylva', 'Yvonne', 'Ylva-Marie', 'Yngvild', 'Yrsa', 'Yasmin', 'Yngvea', 'Yasmine', 'Yliane', 'Yana',
    'Åse', 'Åshild', 'Åsta', 'Ågot', 'Ånette', 'Åsfrid', 'Ådne', 'Åselill', 'Ånna', 'Åline',
  ],
  last: [
    'Aabakken', 'Aaberg', 'Aamot', 'Aarnes', 'Aasen', 'Abrahamsen', 'Andreassen', 'Andresen', 'Antonsen', 'Arnesen',
    'Ask', 'Austad', 'Bakke', 'Bakken', 'Bakkene', 'Bangstad', 'Barli', 'Berg', 'Bergdølmo', 'Birkeland',
    'Bjerke', 'Bjerkan', 'Bjerknes', 'Bjelde', 'Blix', 'Blom', 'Bolstad', 'Borgen', 'Braaten', 'Bragstad',
    'Bratberg', 'Bratseth', 'Brekke', 'Brenden', 'Bronstad', 'Brun', 'Bråten', 'Bø', 'Bøe',
    'Dahl', 'Dahlberg', 'Dahlgren', 'Dahlum', 'Dalen', 'Dale', 'Danielsen',
    'Edvardsen', 'Egeland', 'Eik', 'Eikeland', 'Eikrem', 'Einarsen', 'Ekberg', 'Eliassen', 'Ellefsen', 'Ellingsen', 'Engen', 'Engh', 'Eriksen', 'Evensen',
    'Fagerland', 'Fagerli', 'Fiskerstrand', 'Finstad', 'Fjeld', 'Flatland', 'Foss', 'Fossum', 'Fredriksen', 'Frydenberg',
    'Garberg', 'Gjerde', 'Gjertsen', 'Graham', 'Godal', 'Gran', 'Granheim', 'Grønn', 'Grønvold', 'Gulbrandsen',
    'Haaland', 'Haga', 'Hagen', 'Hakonsen', 'Halvorsen', 'Hansen', 'Haug', 'Haugland', 'Havik', 'Hedenstad', 'Heggem', 'Helle', 'Helland', 'Henriksen', 'Hermansen', 'Hermanrud', 'Hjelle', 'Holm', 'Holmberg', 'Holmen', 'Holstad', 'Holter', 'Horneland', 'Hornseth', 'Hovde', 'Hovland', 'Huseby', 'Husby', 'Haavi', 'Hegerberg', 'Harviken',
    'Ihle', 'Ingebrigtsen', 'Isaksen', 'Iversen',
    'Jacobsen', 'Jahren', 'Jansen', 'Jensen', 'Johannessen', 'Johansen', 'Johnsen', 'Jorgensen', 'Jørgensen',
    'Karlsen', 'Knudsen', 'Knutsen', 'Kristiansen', 'Kristoffersen',
    'Krogstad', 'Kvalheim',
    'Laberg', 'Larsen', 'Lie', 'Lien', 'Lillerud', 'Lindberg', 'Loken', 'Lund', 'Lunde', 'Mjelde', 'Mikalsen', 'Maanum', 'Moen', 'Molde', 'Molskred', 'Myhre', 'Myhrer', 'Myklebust',
    'Nilsen', 'Nordahl', 'Nordberg', 'Nordby', 'Nordeng', 'Nordstrom', 'Nordvik', 'Nygaard', 'Nypan',
    'Olsen', 'Olsson', 'Ostberg', 'Ottesen', 'Overbo',
    'Paulsen', 'Pedersen', 'Pettersen',
    'Panengstuen', 'Rasmussen', 'Reginiussen', 'Reitan', 'Reiten', 'Rise', 'Riseth', 'Roed', 'Rogers', 'Rushfeldt', 'Rød', 'Rønning',
    'Saether', 'Sandberg', 'Sandvik', 'Simonsen', 'Skagen', 'Skjelbred', 'Skjerve', 'Skjold', 'Skjølsvik', 'Skogen', 'Solberg', 'Solheim', 'Sorensen', 'Stenberg', 'Stensrud', 'Storevik', 'Storflor', 'Storvik', 'Strand', 'Stranden', 'Stubhaug', 'Sunde', 'Svenning', 'Svendsen',
    'Tangen', 'Tangvik', 'Tengstedt', 'Terland', 'Thoresen', 'Thorsen', 'Torgersen', 'Tveit', 'Tvedt', 'Tandberg',
    'Ulland',
    'Valø', 'Valsvik', 'Vang', 'Vangen', 'Volden',
    'Wangberg', 'Wiig', 'Winsnes',
    'Åsheim', 'Ødegaard', 'Ødegård', 'Østby', 'Øverland',
  ],
};

export const ENGLISH_NAMES = {
  male: [
    'Aaron', 'Abel', 'Adam', 'Adrian', 'Aidan', 'Alan', 'Albert', 'Alexander', 'Alfred', 'Andrew',
    'Anthony', 'Arthur', 'Austin', 'Barry', 'Benjamin', 'Blake', 'Bradley', 'Brandon', 'Brian', 'Bruce',
    'Caleb', 'Cameron', 'Carl', 'Charles', 'Chris', 'Christopher', 'Colin', 'Connor', 'Corey', 'Craig',
    'Daniel', 'David', 'Dennis', 'Derek', 'Dominic', 'Douglas', 'Dylan', 'Edward', 'Edwin', 'Elliot',
    'Eric', 'Ethan', 'Eugene', 'Evan', 'Felix', 'Francis', 'Frank', 'Fred', 'Gabriel', 'Gavin',
    'George', 'Gordon', 'Grant', 'Gregory', 'Harry', 'Harrison', 'Henry', 'Howard', 'Hugh', 'Ian',
    'Isaac', 'Jack', 'Jacob', 'Jake', 'James', 'Jim', 'Jason', 'Jasper', 'Jeremy', 'John',
    'Johnny', 'Jonathan', 'Jordan', 'Joseph', 'Joshua', 'Julian', 'Justin', 'Keith', 'Kevin', 'Kyle',
    'Lawrence', 'Leo', 'Leonard', 'Liam', 'Logan', 'Louis', 'Luke', 'Malcolm', 'Marcus', 'Mark',
    'Martin', 'Matthew', 'Max', 'Michael', 'Mike', 'Nathan', 'Nathaniel', 'Neil', 'Nicholas', 'Nick',
    'Noah', 'Norman', 'Oliver', 'Oscar', 'Owen', 'Patrick', 'Paul', 'Peter', 'Philip', 'Phillip',
    'Quentin', 'Ralph', 'Raymond', 'Richard', 'Rick', 'Robert', 'Rob', 'Roger', 'Ronald', 'Ross',
    'Ryan', 'Samuel', 'Scott', 'Sean', 'Simon', 'Stephen', 'Steven', 'Stuart', 'Thomas', 'Timothy',
    'Tony', 'Trevor', 'Tristan', 'Tyler', 'Victor', 'Vincent', 'Walter', 'Warren', 'William', 'Will',
    'Zachary', 'Zane', 'Adrian', 'Albert', 'Alfred', 'Alex', 'Allen', 'Anthony', 'Ben', 'Benedict',
    'Brad', 'Brendan', 'Bryan', 'Calvin', 'Carl', 'Cecil', 'Clifford', 'Curtis', 'Damian', 'Dean',
    'Dominic', 'Derek', 'Edgar', 'Elliott', 'Emmett', 'Everett', 'Felix', 'Finn', 'Frederick', 'Gideon',
    'Graham', 'Grayson', 'Hector', 'Hugh', 'Isaiah', 'Jack', 'Jared', 'Joel', 'Jonah', 'Jordan',
    'Julian', 'Keith', 'Landon', 'Lawrence', 'Leon', 'Levi', 'Lloyd', 'Louis', 'Malcolm', 'Mason',
    'Micah', 'Miles', 'Mitchell', 'Nathaniel', 'Nicholas', 'Noel', 'Oliver', 'Owen', 'Patrick', 'Peter',
    'Philip', 'Reuben', 'Richard', 'Robert', 'Roland', 'Ronan', 'Russell', 'Ryan', 'Samuel', 'Sebastian',
    'Simon', 'Spencer', 'Stephen', 'Steven', 'Terrence', 'Thomas', 'Timothy', 'Travis', 'Trevor', 'Victor',
    'Vincent', 'Walter', 'Wesley', 'William', 'Zachary',
  ],
  female: [
    'Abigail', 'Ada', 'Adeline', 'Alice', 'Alicia', 'Allison', 'Amelia', 'Amy', 'Anna', 'Annabelle',
    'Barbara', 'Beatrice', 'Belinda', 'Bernice', 'Beth', 'Betsy', 'Brenda', 'Brianna', 'Brooke', 'Camille',
    ['Catherine', 'Katherine', 'Kate'], 'Cecilia', 'Charlotte', 'Chloe', 'Claire', 'Clara', 'Cynthia', 'Daisy',
    'Deborah', 'Diana', 'Diana', 'Dorothy', 'Edith', 'Eleanor', 'Elizabeth', 'Ella', 'Emily', 'Emma',
    'Erica', 'Evelyn', 'Faith', 'Fiona', 'Frances', 'Gabriella', 'Georgia', 'Grace', 'Hannah', 'Heather',
    'Helen', 'Irene', 'Isabel', 'Isabella', 'Ivy', 'Jacqueline', 'Jane', 'Jasmine', 'Jennifer', 'Jessica',
    'Joanna', 'Julia', 'Juliet', 'Karen', 'Katherine', 'Kimberly', 'Laura', 'Lauren', 'Leah', 'Lillian',
    'Lily', 'Linda', 'Lola', 'Louise', 'Lucia', 'Lucy', 'Madeline', 'Madison', 'Margaret', 'Maria',
    'Marian', 'Marilyn', 'Martha', 'Mary', 'Matilda', 'Megan', 'Melissa', 'Mia', 'Michelle', 'Miranda',
    'Nancy', 'Natalie', 'Nicole', 'Nina', 'Olivia', 'Pamela', 'Patricia', 'Paula', 'Rachel', 'Rebecca',
    'Renee', 'Rose', 'Ruby', 'Samantha', 'Sandra', 'Sarah', 'Savannah', 'Sophia', 'Sophie', 'Stephanie',
    'Susan', 'Sylvia', 'Taylor', 'Theresa', 'Tiffany', 'Tracy', 'Valerie', 'Vanessa', 'Victoria', 'Violet',
    'Virginia', 'Wendy', 'Whitney', 'Abby', 'Alice', 'Amy', 'Anna', 'Audrey', 'Bella', 'Bianca', 'Brenda',
    'Brianna', 'Camilla', 'Carla', 'Caroline', 'Catherine', 'Charlotte', 'Christina', 'Claire', 'Clara', 'Cynthia',
    'Daisy', 'Diana', 'Donna', 'Edith', 'Elaine', 'Eliza', 'Elizabeth', 'Ella', 'Emily', 'Emma',
    'Erica', 'Eva', 'Evelyn', 'Faith', 'Fiona', 'Frances', 'Gabrielle', 'Georgia', 'Grace', 'Hannah',
    'Heather', 'Helen', 'Irene', 'Isabel', 'Isabella', 'Ivy', 'Jacqueline', 'Jane', 'Jasmine', 'Jennifer',
    'Jessica', 'Joanna', 'Julia', 'Juliet', 'Karen', 'Katherine', 'Kimberly', 'Laura', 'Lauren', 'Leah',
    'Lillian', 'Lily', 'Linda', 'Lola', 'Louise', 'Lucia', 'Lucy', 'Madeline', 'Madison', 'Margaret',
    'Maria', 'Marian', 'Marilyn', 'Martha', 'Mary', 'Matilda', 'Megan', 'Melissa', 'Mia', 'Michelle',
  ],
  last: [
    ['Smith', 'Smyth'], ['Johnson', 'Johnston'], 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Wilson', 'Anderson', 'Taylor',
    'Thomas', 'Moore', 'Martin', 'Jackson', 'Thompson', 'White', 'Harris', 'Clark', 'Lewis', 'Robinson',
    'Walker', 'Perez', 'Hall', 'Young', 'Allen', 'Sanchez', 'Wright', 'King', 'Scott', 'Green',
    'Baker', 'Adams', 'Nelson', 'Hill', 'Ramirez', 'Campbell', 'Mitchell', 'Roberts', 'Carter', 'Phillips',
    'Evans', 'Turner', 'Torres', 'Parker', 'Collins', 'Edwards', 'Stewart', 'Flores', 'Morris', 'Nguyen',
    'Murphy', 'Rivera', 'Cook', 'Rogers', 'Morgan', 'Peterson', 'Cooper', 'Reed', 'Bailey', 'Bell',
    'Gomez', 'Kelly', 'Howard', 'Ward', 'Cox', 'Diaz', 'Richardson', 'Wood', 'Watson', 'Brooks',
    'Bennett', 'Gray', 'James', 'Reyes', 'Cruz', 'Hughes', 'Price', 'Myers', 'Long', 'Foster',
    'Sanders', 'Ross', 'Morales', 'Powell', 'Sullivan', 'Russell', 'Ortiz', 'Jenkins', 'Gutierrez', 'Perry',
    'Butler', 'Barnes', 'Fisher', 'Henderson', 'Coleman', 'Simmons', 'Patterson', 'Jordan', 'Reynolds', 'Hamilton',
    'Graham', 'Kim', 'Gonzales', 'Alexander', 'Ramos', 'Wallace', 'Griffin', 'West', 'Cole', 'Hayes',
    'Bryant', 'Herrera', 'Gibson', 'Ellis', 'Tran', 'Medina', 'Aguilar', 'Stevens', 'Murray', 'Ford',
    'Castillo', 'Hamilton', 'Gordon', 'Wagner', 'Willis', 'Ray', 'Watkins', 'Olson', 'Carroll', 'Duncan',
    'Snyder', 'Hart', 'Cunningham', 'Bradley', 'Lane', 'Andrews', 'Ruiz', 'Harper', 'Fox', 'Riley',
    'Armstrong', 'Carpenter', 'Weaver', 'Greene', 'Lawrence', 'Elliott', 'Chavez', 'Sims', 'Austin', 'Peters',
  ],
};

export const SWEDISH_NAMES = {
  male: [
    'Alexander', 'Alfred', 'Albin', 'Anders', 'Anton', 'Arvid', 'Axel', 'Bertil', 'Björn', 'Carl',
    'Claes', 'David', 'Ebbe', 'Edvin', 'Erik', 'Felix', 'Filip', 'Fredrik', 'Gustav', 'Hugo',
    'Isak', 'Jacob', 'Johan', 'Jonas', 'Karl', 'Lars', 'Leon', 'Magnus', 'Matteo', 'Mikael',
    'Niklas', 'Noah', 'Oskar', 'Patrik', 'Per', 'Rasmus', 'Sebastian', 'Simon', 'Sven', 'Theo',
    'Tobias', 'Viktor', 'William', 'Wilhelm', 'Alvar', 'Aron', 'Casper', 'Elias', 'Elmer', 'Filippo',
    'Gustaf', 'Hannes', 'Isak', 'Joel', 'Jonathan', 'Julius', 'Leo', 'Ludvig', 'Max', 'Melker',
    'Nils', 'Oliver', 'Olof', 'Pontus', 'Rafael', 'Richard', 'Samuel', 'Sixten', 'Teodor', 'Valter',
    'Viggo', 'Yngve', 'Åke', 'Örjan',
  ],
  female: [
    'Alice', 'Alma', 'Amelia', 'Astrid', 'Ebba', 'Ella', 'Elin', 'Elvira', 'Emma', 'Frida',
    'Greta', 'Hanna', 'Ida', 'Ingrid', 'Isabella', 'Johanna', 'Julia', 'Kajsa', 'Karin', 'Kristin',
    'Linn', 'Linnea', 'Lovisa', 'Maja', 'Maria', 'Matilda', 'Nellie', 'Nora', 'Olivia', 'Saga',
    'Selma', 'Sofia', 'Stina', 'Therese', 'Tilde', 'Tyra', 'Vendela', 'Vera', 'Wilma', 'Åsa',
    'Alva', 'Alicia', 'Anastasia', 'Anika', 'Annika', 'Caroline', 'Cecilia', 'Clara', 'Diana', 'Ebba',
    'Eira', 'Elena', 'Elisabeth', 'Elsa', 'Estelle', 'Filippa', 'Freja', 'Hedda', 'Hedvig', 'Helena',
    'Ines', 'Jasmine', 'Josefine', 'Junia', 'Klara', 'Livia', 'Märta', 'Sigrid', 'Tyra', 'Ylva',
  ],
  last: [
    'Andersson', 'Johansson', 'Karlsson', 'Nilsson', 'Eriksson', 'Larsson', 'Olsson', 'Persson', 'Svensson', 'Gustafsson',
    'Pettersson', 'Jonsson', 'Jansson', 'Lindberg', 'Lindström', 'Berg', 'Bergström', 'Lund', 'Lundberg', 'Hansson',
    'Holm', 'Forsberg', 'Björk', 'Blom', 'Axelsson', 'Ek', 'Engström', 'Wallin', 'Hedlund', 'Lindqvist',
    'Nyström', 'Fredriksson', 'Arvidsson', 'Bergman', 'Dahl', 'Lind', 'Norberg', 'Lindholm', 'Sjöberg', 'Åkesson',
  ],
};

export const DANISH_NAMES = {
  male: [
    'Alexander', 'Anders', 'Anton', 'Christian', 'Emil', 'Erik', 'Frederik', 'Henrik', 'Jakob', 'Jens',
    'Jonas', 'Kasper', 'Kristian', 'Lars', 'Magnus', 'Mads', 'Martin', 'Mathias', 'Mikkel', 'Nikolaj',
    'Oliver', 'Oscar', 'Philip', 'Rasmus', 'Søren', 'Thomas', 'Thor', 'William', 'Villads', 'Viktor',
    'Alfred', 'Asger', 'August', 'Benjamin', 'Carl', 'Elias', 'Esben', 'Felix', 'Hugo', 'Isak',
    'Jakob', 'Jonathan', 'Julius', 'Liam', 'Lucas', 'Malthe', 'Noah', 'Oskar', 'Sebastian', 'Viggo',
  ],
  female: [
    'Agnes', 'Alma', 'Anna', 'Caroline', 'Clara', 'Emma', 'Freja', 'Ida', 'Ingrid', 'Josefine',
    'Julie', 'Karoline', 'Laura', 'Liva', 'Mathilde', 'Mille', 'Nora', 'Olivia', 'Signe', 'Sofie',
    'Victoria', 'Asta', 'Astrid', 'Emilie', 'Ella', 'Eline', 'Filippa', 'Hannah', 'Isabella', 'Josephine',
    'Kaja', 'Kristine', 'Lea', 'Linnea', 'Maja', 'Mille', 'Nanna', 'Sara', 'Sofie', 'Thea',
    'Alberte', 'Amalie', 'Andrea', 'Anine', 'Aurora', 'Clara', 'Esther', 'Frida', 'Greta', 'Hedvig',
  ],
  last: [
    'Jensen', 'Nielsen', 'Hansen', 'Pedersen', 'Andersen', 'Christensen', 'Larsen', 'Sørensen', 'Rasmussen', 'Jørgensen',
    'Petersen', 'Madsen', 'Kristensen', 'Olsen', 'Thomsen', 'Christoffersen', 'Johansen', 'Møller', 'Mortensen', 'Knudsen',
    'Lund', 'Berg', 'Holm', 'Lind', 'Nørgaard', 'Høgh', 'Bjerre', 'Vestergaard', 'Fischer', 'Bech',
  ],
};

export const FRENCH_NAMES = {
  male: [
    'Adrien', 'Alexandre', 'Alphonse', 'Antoine', 'Benjamin', 'Charles', 'Christophe', 'Damien', 'David', 'Denis',
    'Emmanuel', 'Etienne', 'François', 'Gabriel', 'Gaspard', 'Guillaume', 'Hugo', 'Jacques', 'Jean', 'Julien',
    'Laurent', 'Louis', 'Lucas', 'Marc', 'Mathieu', 'Michel', 'Nicolas', 'Olivier', 'Pierre', 'Quentin',
    'Raphaël', 'Rémi', 'Richard', 'Romain', 'Samuel', 'Sébastien', 'Simon', 'Stéphane', 'Thomas', 'Victor',
    'Vincent', 'Yann', 'Alexis', 'Arnaud', 'Benoît', 'Clément', 'Éric', 'Fabien', 'Florian', 'Franck',
  ],
  female: [
    'Adeline', 'Agathe', 'Alice', 'Amélie', 'Anaïs', 'Anne', 'Audrey', 'Camille', 'Caroline', 'Cécile',
    'Charlotte', 'Chloé', 'Claire', 'Clémence', 'Élise', 'Élodie', 'Émilie', 'Estelle', 'Florence', 'Gabrielle',
    'Hélène', 'Inès', 'Isabelle', 'Julie', 'Justine', 'Laure', 'Léa', 'Lise', 'Lucie', 'Madeleine',
    'Manon', 'Margaux', 'Marie', 'Mathilde', 'Mélanie', 'Nathalie', 'Océane', 'Sophie', 'Stéphanie', 'Valérie',
    'Vanessa', 'Victoria', 'Yasmine', 'Édith', 'Aurélie', 'Catherine', 'Anaëlle', 'Solène', 'Éva', 'Louna',
  ],
  last: [
    'Martin', 'Bernard', 'Thomas', 'Petit', 'Robert', 'Richard', 'Durand', 'Dubois', 'Moreau', 'Laurent',
    'Simon', 'Michel', 'Lefebvre', 'Leroy', 'Roux', 'David', 'Bertrand', 'Morel', 'Fournier', 'Girard',
    'Bonnet', 'Dupont', 'Lambert', 'Fontaine', 'Rousseau', 'Blanc', 'Garnier', 'Chevalier', 'François', 'Mercier',
    'Dupuis', 'Moulin', 'Marchand', 'Barbier', 'Gauthier', 'Guillet', 'Colin', 'Perrin', 'Jacquet', 'Lemoine',
  ],
};

export const GERMAN_NAMES = {
  male: [
    'Alexander', 'Andreas', 'Benjamin', 'Christian', 'Daniel', 'David', 'Dominik', 'Felix', 'Florian', 'Frank',
    'Gabriel', 'Hans', 'Jakob', 'Jan', 'Johannes', 'Jonas', 'Julius', 'Karl', 'Leon', 'Lukas',
    'Markus', 'Matthias', 'Maximilian', 'Michael', 'Niklas', 'Oliver', 'Paul', 'Philipp', 'Rafael', 'Sebastian',
    'Simon', 'Stefan', 'Thomas', 'Tobias', 'Valentin', 'Vincent', 'Werner', 'Wolfgang', 'Adrian', 'Anton',
    'Benjamin', 'David', 'Emil', 'Erik', 'Fabian', 'Hannes', 'Jakob', 'Johann', 'Jonas', 'Lennart',
  ],
  female: [
    'Anna', 'Amelie', 'Clara', 'Emilia', 'Emma', 'Hannah', 'Ida', 'Isabella', 'Johanna', 'Julia',
    'Katharina', 'Laura', 'Lea', 'Lena', 'Lina', 'Luisa', 'Marie', 'Maria', 'Mia', 'Nina',
    'Sophie', 'Sophia', 'Theresa', 'Vanessa', 'Victoria', 'Franziska', 'Caroline', 'Annika', 'Greta', 'Helena',
    'Leonie', 'Paula', 'Luise', 'Amalia', 'Alina', 'Marlene', 'Claudia', 'Sarah', 'Melanie', 'Jasmin',
    'Eva', 'Ella', 'Frida', 'Leona', 'Lilly', 'Jana', 'Alina', 'Rosalie', 'Mathilda', 'Elena',
  ],
  last: [
    'Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Schulz', 'Hoffmann',
    'Schäfer', 'Koch', 'Bauer', 'Richter', 'Klein', 'Wolf', 'Schröder', 'Neumann', 'Schwarz', 'Zimmermann',
    'Braun', 'Krüger', 'Hofmann', 'Hartmann', 'Lange', 'Schmitt', 'Werner', 'Schmitz', 'Krause', 'Meier',
    'Lehmann', 'Schmid', 'Schulze', 'Maier', 'Köhler', 'Herrmann', 'Walter', 'König', 'Fuchs', 'Vogel',
  ],
};

export const ITALIAN_NAMES = {
  male: [
    'Alessandro', 'Andrea', 'Antonio', 'Davide', 'Diego', 'Emiliano', 'Enrico', 'Fabio', 'Federico', 'Filippo',
    'Francesco', 'Gabriele', 'Giovanni', 'Giuseppe', 'Lorenzo', 'Luca', 'Marco', 'Matteo', 'Niccolò', 'Nicola',
    'Paolo', 'Pietro', 'Riccardo', 'Roberto', 'Samuele', 'Simone', 'Stefano', 'Tommaso', 'Vincenzo', 'Alberto',
    'Emanuele', 'Giorgio', 'Leonardo', 'Mattia', 'Raffaele', 'Salvatore', 'Sandro', 'Tiziano', 'Valerio', 'Vittorio',
  ],
  female: [
    'Alessia', 'Alice', 'Anna', 'Beatrice', 'Chiara', 'Elena', 'Federica', 'Francesca', 'Giorgia', 'Giulia',
    'Ilaria', 'Laura', 'Ludovica', 'Martina', 'Marta', 'Maria', 'Noemi', 'Sofia', 'Silvia', 'Valentina',
    'Vanessa', 'Veronica', 'Vittoria', 'Camilla', 'Claudia', 'Daniela', 'Eleonora', 'Giovanna', 'Lucia', 'Nicoletta',
    'Paola', 'Roberta', 'Sara', 'Simona', 'Stefania', 'Alberta', 'Angelica', 'Aurora', 'Beatrice', 'Carlotta',
  ],
  last: [
    'Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco',
    'Bruno', 'Gallo', 'Conti', 'De Luca', 'Mancini', 'Costa', 'Giordano', 'Rizzo', 'Lombardi', 'Moretti',
    'Barbieri', 'Fontana', 'Santoro', 'Mariani', 'Rinaldi', 'Caruso', 'Ferrara', 'Galli', 'Martini', 'Leone',
  ],
};

export const SPANISH_NAMES = {
  male: [
    'Adrián', 'Alejandro', 'Alfonso', 'Álvaro', 'Andrés', 'Antonio', 'Carlos', 'Daniel', 'David', 'Diego',
    'Eduardo', 'Enrique', 'Fernando', 'Francisco', 'Gabriel', 'Gerardo', 'Gonzalo', 'Guillermo', 'Héctor', 'Ignacio',
    'Javier', 'Jesús', 'José', 'Juan', 'Julián', 'Luis', 'Manuel', 'Marcos', 'Martín', 'Miguel',
    'Pablo', 'Pedro', 'Rafael', 'Raúl', 'Roberto', 'Santiago', 'Sergio', 'Tomás', 'Vicente', 'Víctor',
  ],
  female: [
    'Adriana', 'Alejandra', 'Alma', 'Ana', 'Beatriz', 'Carla', 'Carmen', 'Clara', 'Daniela', 'Elena',
    'Elisa', 'Emilia', 'Esperanza', 'Fernanda', 'Gabriela', 'Isabel', 'Jimena', 'Juana', 'Laura', 'Lucía',
    'Margarita', 'María', 'Marina', 'Marta', 'Natalia', 'Patricia', 'Raquel', 'Rosa', 'Sara', 'Silvia',
    'Sofía', 'Teresa', 'Valentina', 'Verónica', 'Victoria', 'Yolanda', 'Zoe', 'Carlota', 'Alicia', 'Inés',
  ],
  last: [
    'García', 'Martínez', 'López', 'Sánchez', 'Pérez', 'González', 'Rodríguez', 'Fernández', 'Gómez', 'Ruiz',
    'Hernández', 'Jiménez', 'Díaz', 'Morales', 'Alonso', 'Romero', 'Navarro', 'Torres', 'Domínguez', 'Vázquez',
    'Ramos', 'Gil', 'Ramírez', 'Serrano', 'Blanco', 'Molina', 'Suárez', 'Ortega', 'Delgado', 'Castillo',
  ],
};
